# Generated by Django 2.2.1 on 2019-06-01 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_auto_20190531_1603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='received_by',
            new_name='receiver',
        ),
        migrations.RenameField(
            model_name='email',
            old_name='created_by',
            new_name='sender',
        ),
    ]
