# Generated by Django 2.2.1 on 2019-06-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_auto_20190531_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='email',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
