# Generated by Django 2.2.1 on 2019-06-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_auto_20190606_0055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ['-created_at']},
        ),
    ]
