# Generated by Django 2.2.1 on 2019-06-14 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_auto_20190606_0224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='URI',
            new_name='object_name',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='attached_to',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='email',
            name='attachment',
        ),
        migrations.AddField(
            model_name='attachment',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attachments', to='emails.Email'),
        ),
    ]
