# Generated by Django 2.2.1 on 2019-06-18 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_userinbox_userstarred_usertrash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinbox',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userinbox',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userstarred',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userstarred',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='usertrash',
            old_name='email_id',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='usertrash',
            old_name='user_id',
            new_name='user',
        ),
    ]
