# Generated by Django 2.2.1 on 2019-06-20 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0008_auto_20190618_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinbox',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.Email'),
        ),
        migrations.AlterField(
            model_name='userinbox',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inbox', to=settings.AUTH_USER_MODEL),
        ),
    ]
