# Generated by Django 2.2.1 on 2019-06-21 03:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emails', '0009_auto_20190620_1515'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInbox',
            new_name='Inbox',
        ),
        migrations.RenameModel(
            old_name='UserStarred',
            new_name='Starred',
        ),
        migrations.RenameModel(
            old_name='UserTrash',
            new_name='Trash',
        ),
    ]
