# Generated by Django 2.2.1 on 2019-06-24 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0010_auto_20190620_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trash',
            name='email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='emails.Email'),
        ),
        migrations.AlterField(
            model_name='trash',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trash', to=settings.AUTH_USER_MODEL),
        ),
    ]
